### ISSUE TITLE
M1 Mac compatibility

### ISSUE THREAD

**Issue by JohnLockeNJ** [amitv87/PiP#16]
Would you considering creating a version that will work on the M1 Mac? Using it now just creates a black screen.

Or perhaps there's a fix that could make the Intel version work on M1 Macs, even if it's not optimized?

**Comment by amitv87** [comment]
ALthough the app runs fine using Rosetta 2, I have published a new build with fat binary https://github.com/amitv87/PiP/releases/tag/v1.41

**Comment by amitv87** [comment]
The reported black screen appear from ghost windows (these are usually overlay/info windows which are always hidden).
There's no specific property associated with those windows which can be used to differentiate from normal windows.
Although the ghost windows have empty window title (can be seen in right click menu), but it is not a proper way to restrict them.

**Comment by jonfoxnj** [comment]
I’m still having the same issue on the latest 1.5 build on an M1 Mac. Black screen.

**Comment by amitv87** [comment]
> I’m still having the same issue on the latest 1.50(7) build on an M1 Mac. Black screen.

Can you share a video showing the same?

**Comment by amitv87** [comment]
The release https://github.com/amitv87/PiP/releases/tag/v2.03 exclodes ghost windows by default.
